
name: Action

on:
  workflow_dispatch:

    inputs:
      shell:
        description: 'shell'
        required: true
        default: 'ls ; '
        
      ssh:
        description: 'ssh'
        required: true
        default: 'false'
        type: boolean   

      clear:
        description: 'clear?'
        required: true
        default: 'false'
        type: boolean   

jobs:
    build:
      runs-on: windows-latest

      steps:
        - name: 获取本仓库源码
          uses: actions/checkout@main
        
        - name: 打扫空间
          if: github.event.inputs.clear == 'true'
          run: |       
              curl -sL https://raw.github.com/zhlhlf/text/main/cleanup.sh | bash
              
        - name: 操作
          run: |       
              mkdir 666
              ${{ github.event.inputs.shell }}
              aria2c -x10 "https://down.wss.show/dghuz21/c/ts/ctstdghuz21?cdn_sign=1701713808-38-0-022169826b3c3e53fb7e19f718eb3229&exp=1200&response-content-disposition=attachment%3B%20filename%3D%22Meteoric-KernelSU-V12-230927-2230.zip%22%3B%20filename%2A%3Dutf-8%27%27Meteoric-KernelSU-V12-230927-2230.zip" -o a.zip 
              unzip a.zip
              dir
              ./find_load_module.exe Image
              
        - name: 高级操作
          if: github.event.inputs.ssh == 'true'
          run: |
            curl -SL http://raw.github.com/zhlhlf/text/main/ssh.sh | sudo bash    
    
              
    
